<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Java Streams' Course: Terminal Stream Operations</description>
    <name>terminal-stream-operations</name>

    <groupId>com.baeldung</groupId>
    <artifactId>ljs-terminal-stream-operations</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>any-all-none-match-start</module>
        <module>any-all-none-match-end</module>
        <module>common-operations-patterns-start</module>
        <module>common-operations-patterns-end</module>
        <module>count-min-max-start</module>
        <module>count-min-max-end</module>
        <module>find-first-find-any-start</module>
        <module>find-first-find-any-end</module>
        <module>groupingby-partitioningby-start</module>
        <module>groupingby-partitioningby-end</module>
        <module>reduce-start</module>
        <module>reduce-end</module>
        <module>tomap-tolist-toset-start</module>
        <module>tomap-tolist-toset-end</module>
    </modules>
</project>
